version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "app_user"
      POSTGRES_PASSWORD: "change_me"
      POSTGRES_DB: "demo_app"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - main

networks:
  main:
volumes:
  db-data: